version: '3.8'

services:
  worker:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: callsbot-worker
    command: ["python", "scripts/bot.py", "run"]
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - CALLSBOT_LOG_STDOUT=true
      - CALLSBOT_METRICS_ENABLED=true
      - CALLSBOT_FORCE_FALLBACK=false
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./var:/app/var
      - ./data/logs:/app/data/logs
    ports:
      - "9108:9108"
    depends_on:
      - redis
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  web:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: callsbot-web
    command: ["gunicorn", "-k", "gthread", "--threads", "4", "-w", "2", "-t", "120", "--graceful-timeout", "30", "-b", "0.0.0.0:8080", "src.server:create_app()"]
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DASH_PORT=8080
      - CALLSBOT_LOG_STDOUT=true
      - CALLSBOT_SQL_KEY=${CALLSBOT_SQL_KEY}
    volumes:
      - ./var:/app/var
      - ./data/logs:/app/data/logs:ro
    expose:
      - "8080"
    healthcheck:
      disable: true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  trader:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: callsbot-trader
    command: ["python", "-m", "tradingSystem.cli"]
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - CALLSBOT_LOG_STDOUT=true
    volumes:
      - ./var:/app/var
      - ./data/logs:/app/data/logs
    depends_on:
      - worker
      - web
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  tracker:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: callsbot-tracker
    command: ["python", "scripts/track_performance.py"]
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - CALLSBOT_LOG_STDOUT=true
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./var:/app/var
      - ./data/logs:/app/data/logs
    depends_on:
      - worker
      - redis
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    container_name: callsbot-redis
    restart: unless-stopped
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru --save ""
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"

  caddy:
    image: caddy:2
    container_name: callsbot-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  caddy_data:
  caddy_config:
  redis_data:
